[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.32"
color-eyre = "*"          # error handling
handlebars = "6.3.1"      # templating
lazy_static = "1.5.0"
log = "0.4.26"
maud = "0.26.0"           # html macro
pulldown-cmark = "0.11.0" # markdown to html
serde = { version = "1.0.219", features = ["derive"] }
simple_logger = "5.0.0"
toml = "0.8.20"           # toml parser

[dev-dependencies]
filetime = "0.2.25"
tempfile = "3.18.0"
